from func_gener import random_number, date_time
from open_files import terminal
def acq():    
    ACQ = f"""<Doc>
            <Trans Type>
                <TransCode>
                    <FinCategory>N</FinCategory>
                    <RequestCategory>P</RequestCategory>
                    <ServiceClass>T</ServiceClass>
                    <TransTypeCode>I5</TransTypeCode>
                </TransCode>
                <TransCondition>TERM, TERM_TRACK, ONLINE, CARD, READ_TRACK</TransCondition>
            </TransType>
            <DocRefSet>
                <Parm>
                    <ParmCode>ARN</ParmCode>
                    <Value>{random_number(24)}</Value> //17213140307741314030774
                </Parm>
                <Parm>
                    <ParmCode>IRN</ParmCode>
                    <Value></Value>
                </Parm>
                <Parm>
                    <ParmCode>AuthCode</ParmCode>
                    <Value>{random_number(6)}</Value> //030790
                </Parm>
                <Parm>
                    <ParmCode>RRN</ParmCode>
                    <Value>721314030790</Value>
                </Parm>
                <Parm>
                    <ParmCode>TRN</ParmCode>
                    <Value>406500007709972</Value>
                </Parm>
            </DocRefSet>
            <LocalDt>{date_time()}</LocalDt> //2024-07-17 05:47:10
            <NWDt>{date_time()}</NWDt>
            <SourceDtis>
                <SIC>7298</SIC>
                <Country>RUS</Country>
                <City>Moscow</City>
                <MerchantName>Tst spec 1</MerchantName>
                <MerchantID>{terminal['value']}</MerchantID>
            </SourceDtis>
            <Originator>
                <ContractNumber>{terminal['access_number']}</ContractNumber> //W9812138
                <Transitid>888887</TransitId>
            </Originator>
            <Destination>
                <ContractNumber>5426546609014797</ContractNumber>
                <CardInfo>
                    <CardExpiry>2512</CardExpiry>
                </CardInfo>
                <Product>
                    <Channel>E</Channel>
                </Product>
            </Destination>
            <Transaction>
                <Currency>810</Currency>
                <Amount>654.00</Amount>
                <Extra>
                    <Type>AddInfo</Type>
                    <AddData>
                        <Parm>
                            <ParmCode>OUT_ST</ParmCode>
                            <Value>C</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>ACQ_TKB_ROUTING</ParmCode>
                            <Value>Y</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Crt</ParmCode>
                            <Value>MIR</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Pcd</ParmCode>
                            <Value>000</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Typ</ParmCode>
                            <Value>005</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_CNUM</ParmCode>
                            <Value>000026709972</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Capt_Dat</ParmCode>
                            <Value>260324</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Auth_Num</ParmCode>
                            <Value>14030790</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Vendor_ID</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Add_Info</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_RecDat</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Fee</ParmCode>
                            <Value>0000000000</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Comission</ParmCode>
                            <Value>0000000000</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_Receiver</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_SETTLE_AMT</ParmCode>
                            <Value>0.00</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_SETTLE_FEE</ParmCode>
                            <Value>0.00</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_SETTLE_CUR</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_SETTLE_DATE</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_SETTLE_BANK</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>ITN</ParmCode>
                            <Value>1234567890</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_VTB24_CRD</ParmCode>
                            <Value>0</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_CVM</ParmCode>
                            <Value>4</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>M_PAY_TECH</ParmCode>
                            <Value>0</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_3DS</ParmCode>
                            <Value>0</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>M_RRN_IPSP</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_S_MRCH_NAM</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_EXT_DAT</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_T_ENT</ParmCode>
                            <Value>8</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_T_CNTLESS</ParmCode>
                            <Value>1</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_MPOSI</ParmCode>
                            <Value>0</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_P2P_NAM</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_P2P_CRD</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_CRD_PROD</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_PSPD</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MC_WALLET_DATA</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_T_ADR</ParmCode>
                            <Value>5, Zvezdniy pr</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_T_ZIP</ParmCode>
                            <Value>1234567890</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_F32</ParmCode>
                            <Value>70290240102</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MK_MC_ASSIGN_ID</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>VISA_MW</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>UNI</ParmCode>
                            <Value></Value>
                        </Parm>
                        <Parm>
                            <ParmCode>M_HOST</ParmCode>
                            <Value>TWO TK</Value>
                        </Parm>
                        <Parm>
                            <ParmCode>MEMBER_ID_ACQ</ParmCode>
                            <Value>888877</Value>
                        </Parm>
                    </AddData>
                </Extra>
            </Transaction>
        </Doc>"""
    return ACQ